
[control_plane]
k3s-control-plane ansible_host=2.28.13.206

[workers]
k3s-worker-1 ansible_host=2.28.5.139
k3s-worker-2 ansible_host=167.233.222.204

[k3s_cluster:children]
control_plane
workers

[all:vars]
ansible_user=artur